de: Hallo! Wie kann ich Ihnen heute helfen?
en: Hello! How can I help you today?
es: ¡Hola! ¿En qué te puedo ayudar?
fr: Bonjour ! Comment puis-je vous aider aujourd’hui ?
fr-CA: Bonjour! Comment puis-je vous aider aujourd’hui?
